### ISSUE TITLE
Uncaught TypeError: clipboard.readImage(...).toPng is not a function

### ISSUE THREAD

**Issue by hakuseki** [asciidoctor/atom-asciidoc-image-helper#19]
[Enter steps to reproduce:]

1. Copy an image to clipboard
2. Paste in asciiddoc document

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Mac OS X 10.13.5
**Thrown From**: [asciidoc-image-helper](https://github.com/asciidoctor/atom-asciidoc-image-helper) package 1.0.0

### Stack Trace

Uncaught TypeError: clipboard.readImage(...).toPng is not a function

```
At /Users/mgr/.atom/packages/asciidoc-image-helper/lib/main.coffee:51

TypeError: clipboard.readImage(...).toPng is not a function
    at Object.pasteNativeImage (/packages/asciidoc-image-helper/lib/main.coffee:51:39)
    at /packages/asciidoc-image-helper/lib/main.coffee:35:12
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:360:24)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -1:51.2.0 editor:select-to-end-of-line (input.hidden-input)
     -1:50.7.0 core:select-left (input.hidden-input)
     -1:50 core:backspace (input.hidden-input)
  5x -1:46 core:move-down (input.hidden-input)
  2x -1:42.3.0 editor:newline (input.hidden-input)
  6x -1:32.7.0 core:move-left (input.hidden-input)
     -1:30 editor:move-to-end-of-screen-line (input.hidden-input)
 15x -1:15.9.0 core:backspace (input.hidden-input)
     -1:13.5.0 autocomplete-plus:confirm (input.hidden-input)
     -1:13.5.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:13.3.0 editor:newline (input.hidden-input)
  2x -1:12.2.0 core:backspace (input.hidden-input)
     -1:10.2.0 core:move-right (input.hidden-input)
     -1:08.8.0 editor:select-to-end-of-line (input.hidden-input)
     -1:08.1.0 core:backspace (input.hidden-input)
  2x -1:07.3.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
asciidoc-assistant 0.2.2 
asciidoc-image-helper 1.0.0 
asciidoc-preview 2.12.1 
atom-beautify 0.32.5 
atom-grails 1.2.0 
atom-language-velocity 1.1.0 
atomic-chrome 0.3.3 
autocomplete 0.47.0 
autocomplete-asciidoc 0.1.2 
autocomplete-java 1.2.7 
autocomplete-xml 0.10.1 
darkula-ui 0.1.0 
dash 1.7.1 
file-icons 2.1.21 
intellij-idea-keymap 0.2.3 
java-generator 2.2.3 
language-asciidoc 1.11.0 
language-groovy 0.7.0 
language-kotlin 0.5.0 
language-plantuml 0.2.0 
minimap 4.29.8 
native-ui 0.26.2 
pigments 0.40.2 
plantuml-viewer 0.7.2 
pretty-json 2.0.1 
Quick-JavaScript 2.2.0 
slime 2.4.0 
split-diff 1.5.2 
teletype 0.13.3 
xml-formatter 0.11.0 
```

**Comment by sweepingmonk123** [comment]
is this problem solved? that function is very impoortant to me, that effects a lot.

**Comment by ldez** [comment]
Fixed in v1.0.1

**Comment by sweepingmonk123** [comment]
great!!!thanks a lot

**Comment by sweepingmonk123** [comment]
i upgrade the version, it worked ,thanks a lot.

**Comment by tonyeen** [comment]
It's been a long time coming. Thank you!

**Comment by hakuseki** [comment]
Thx
